<a href="https://colab.research.google.com/github/Fourierfantastic/ML_File/blob/main/GridSearchCV.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [ ]:
df = sns.load_dataset("iris")

In [ ]:
df

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [ ]:
df.columns

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')

In [ ]:
df['species'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [ ]:
from sklearn.model_selection import train_test_split
X = df.drop("species",axis=1)
y = df["species"]

In [ ]:


X_train, X_test, y_train, y_test = train_test_split(
X, y, test_size=0.2, random_state=42)

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
model_knn = KNeighborsClassifier(n_neighbors=13)

model_knn.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=13)

In [ ]:
model_knn.score(X_test,y_test)

1.0

In [ ]:
from sklearn.svm import SVC
model_svm = SVC(gamma='auto')
model_svm.fit(X_train,y_train)

SVC(gamma='auto')

In [ ]:
model_svm.score(X_test,y_test)

1.0

Now lets use GrigSearch CV

In [ ]:
from sklearn.model_selection import GridSearchCV
classifier = GridSearchCV((model_svm),{
    'C' : [1,10,20,30],
    'kernel' : ['rbf','linear']
},cv = 5,return_train_score = False)

classifier.fit(X,y)

GridSearchCV(cv=5, estimator=SVC(gamma='auto'),
             param_grid={'C': [1, 10, 20, 30], 'kernel': ['rbf', 'linear']})

In [ ]:
classifier.cv_results_

{'mean_fit_time': array([0.00316663, 0.00237684, 0.00239863, 0.0021924 , 0.00225005,
        0.00223665, 0.00222807, 0.00209618]),
 'std_fit_time': array([1.26266900e-03, 1.11742228e-04, 7.67050930e-05, 6.89122250e-05,
        4.88732733e-05, 1.88016801e-04, 9.24618358e-05, 5.51329754e-05]),
 'mean_score_time': array([0.00235968, 0.00179009, 0.00174985, 0.00174379, 0.00166535,
        0.00161805, 0.00163145, 0.00157785]),
 'std_score_time': array([1.00591424e-03, 6.14919186e-05, 3.25971824e-05, 1.29971675e-04,
        3.85112063e-05, 1.91018371e-05, 2.43940308e-05, 1.39827974e-05]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20, 30, 30],
              mask=[False, False, False, False, False, False, False, False],
        fill_value=999999),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear',
                    'rbf', 'linear'],
              mask=[False, False, False, False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'linear'},
  {'C': 30, 'kernel': 'rbf'},
  {'C': 30, 'kernel': 'linear'}],
 'split0_test_score': array([0.96666667, 0.96666667, 0.96666667, 1.        , 0.96666667,
        1.        , 0.96666667, 1.        ]),
 'split1_test_score': array([1., 1., 1., 1., 1., 1., 1., 1.]),
 'split2_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.9       , 0.9       ,
        0.9       , 0.9       , 0.9       ]),
 'split3_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
        0.93333333, 0.93333333, 0.9       ]),
 'split4_test_score': array([1., 1., 1., 1., 1., 1., 1., 1.]),
 'mean_test_score': array([0.98      , 0.98      , 0.98      , 0.97333333, 0.96666667,
        0.96666667, 0.96      , 0.96      ]),
 'std_test_score': array([0.01632993, 0.01632993, 0.01632993, 0.03887301, 0.03651484,
        0.0421637 , 0.03887301, 0.04898979]),
 'rank_test_score': array([1, 1, 1, 4, 5, 6, 7, 7], dtype=int32)}

In [ ]:
results = pd.DataFrame(classifier.cv_results_)

In [ ]:
results

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.003939,0.000391,0.002924,0.000198,1,rbf,"{'C': 1, 'kernel': 'rbf'}",1.000000,0.958333,0.833333,1.000000,0.958333,0.950000,0.061237,3
1,0.003509,0.000095,0.002729,0.000149,1,linear,"{'C': 1, 'kernel': 'linear'}",1.000000,0.958333,0.875000,1.000000,0.958333,0.958333,0.045644,1
2,0.003598,0.000112,0.003136,0.000787,10,rbf,"{'C': 10, 'kernel': 'rbf'}",1.000000,0.958333,0.833333,1.000000,1.000000,0.958333,0.064550,1
3,0.008658,0.000438,0.007747,0.000233,10,linear,"{'C': 10, 'kernel': 'linear'}",1.000000,0.958333,0.833333,0.958333,1.000000,0.950000,0.061237,3
4,0.005520,0.002459,0.003468,0.000923,20,rbf,"{'C': 20, 'kernel': 'rbf'}",0.958333,0.958333,0.833333,1.000000,1.000000,0.950000,0.061237,3
5,0.003679,0.000144,0.002842,0.000141,20,linear,"{'C': 20, 'kernel': 'linear'}",0.958333,0.958333,0.833333,1.000000,1.000000,0.950000,0.061237,3
6,0.003857,0.000187,0.003038,0.000149,30,rbf,"{'C': 30, 'kernel': 'rbf'}",0.958333,0.958333,0.833333,1.000000,0.958333,0.941667,0.056519,8
7,0.005777,0.002698,0.005032,0.001892,30,linear,"{'C': 30, 'kernel': 'linear'}",0.958333,0.958333,0.833333,0.958333,1.000000,0.941667,0.056519,7

In [ ]:

results[['param_C','param_kernel','mean_test_score']]

   param_C param_kernel  mean_test_score
0        1          rbf         0.950000
1        1       linear         0.958333
2       10          rbf         0.958333
3       10       linear         0.950000
4       20          rbf         0.950000
5       20       linear         0.950000
6       30          rbf         0.941667
7       30       linear         0.941667

In [ ]:


from sklearn.model_selection import RandomizedSearchCV


classifier_r = RandomizedSearchCV((model_svm),{
    'C' : [1,10,20,30],
    'kernel' :['rbf','linear'],
},n_iter = 4,cv = 5,return_train_score = False)


classifier_r.fit(X,y)

RandomizedSearchCV(cv=5, estimator=SVC(gamma='auto'), n_iter=4,
                   param_distributions={'C': [1, 10, 20, 30],
                                        'kernel': ['rbf', 'linear']})

In [ ]:

results = pd.DataFrame(classifier_r.cv_results_)

In [ ]:
results

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_kernel,param_C,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.002794,0.00053,0.002188,0.000719,rbf,1,"{'kernel': 'rbf', 'C': 1}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
1,0.002331,0.00010,0.001774,0.000215,rbf,20,"{'kernel': 'rbf', 'C': 20}",0.966667,1.0,0.900000,0.966667,1.0,0.966667,0.036515,2
2,0.002165,0.00009,0.001614,0.000021,linear,20,"{'kernel': 'linear', 'C': 20}",1.000000,1.0,0.900000,0.933333,1.0,0.966667,0.042164,3
3,0.002181,0.00002,0.001690,0.000035,rbf,30,"{'kernel': 'rbf', 'C': 30}",0.966667,1.0,0.900000,0.933333,1.0,0.960000,0.038873,4

In [ ]:
results[['param_C','param_kernel','mean_test_score']]

   param_C param_kernel  mean_test_score
0        1          rbf         0.980000
1       20          rbf         0.966667
2       20       linear         0.966667
3       30          rbf         0.960000

In [ ]:
%ls

sample_data/

In [ ]:
!ls/content

/bin/bash: line 1: ls/content: No such file or directory

In [ ]:
!ls /content/drive/MyDrive

ls: cannot access '/content/drive/MyDrive': No such file or directory

In [ ]:
!find/content -GridSearchCV "data.ipynb"

/bin/bash: line 1: find/content: No such file or directory

In [ ]:
!ls /content/drive/MyDrive

ls: cannot access '/content/drive/MyDrive': No such file or directory

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
!ls /content/drive/MyDrive

'Colab Notebooks'

In [ ]:
os.listdir('/content/drive/MyDrive/Colab Notebooks')

['GridSearchCV.ipynb', 'TitanicModel.ipynb', 'Untitled0.ipynb']

In [ ]:
import os
os.listdir('/content/drive/MyDrive')

['Colab Notebooks']